---
deployment:
  tasks:
    - export DEPLOYPATH=/repositories/nepse
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage/framework $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .composer.json $DEPLOYPATH
    - /bin/cp .composer.lock $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp server.php $DEPLOYPATH